# Site settings
title: Chris LaBarge
email: chrislabarge2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chrislabarge.github.io" # the base hostname & protocol for your site
twitter_username: clabvessels
github_username:  ChrisLaBarge
paginate: 4
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed